defaults:
    - _self_
    - data: nabirds
    - optimizer: Adam
    - model: MetaFG_2.yaml

random_seed: 8
epoch: 100
print_freq: 20
valid_freq: 5

data:
    batch_size:
        train: 64
        valid: 64
    transform:
        train:
            RandomResizedCrop:
                width: 224
                height: 224
            RandomRotate90: { }
            HorizontalFlip:
                p: 0.5
            CoarseDropout:
                max_holes: 8
                max_height: 8
                max_width: 8
                min_holes: 4
                min_height: 4
                min_width: 4
                p: 0.5
        valid:
            Resize:
                width: 224
                height: 224

#scheduler:
#    type: MultiStepLR
#    args: {}
criterion:
    name: CrossEntropyLoss
    params: {}

wandb:
    entity: errolseo
    project: test
    name: test01
