base:
    save_dir: save/classification
    random_seed: 8
    epoch: 100
    amp: O1
data:
    type: ImageFolder
    path:
        train: /workspace/nabirds/images
        valid: /workspace/nabirds/images
    ratio: 0.8
    batch_size:
        train: 256
        valid: 256
    transform:
        train:
            RandomResizedCrop:
                width: 224
                height: 224
            RandomRotate90: {}
            HorizontalFlip:
                p: 0.5
            CoarseDropout:
                max_holes: 8
                max_height: 8
                max_width: 8
                min_holes: 4
                min_height: 4
                min_width: 4
                p: 0.5
        valid:
            Resize:
                width: 224
                height: 224
model:
    type: timm
    name: vit_base_patch16_224
    params:
        pretrained: True
        num_classes: 555
    # microsoft/beit-base-patch16-224-pt22k
    # microsoft/beit-base-patch16-224
criterion:
    name: CrossEntropyLoss
    params: {}
optimizer:
    name: AdamW
    params:
        lr: 2e-4
#scheduler:
#    type: MultiStepLR
#    args: {}
wandb:
    entity: hes
    project: test
    name: test01
